spring:
  application:
    name: dietitian_plus

  datasource:
    url: jdbc:mysql://localhost:3306/dietitian_plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: rootpassword

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090
